// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// vsemC
NumericMatrix vsemC(NumericVector par, NumericVector PAR);
RcppExport SEXP BayesianTools_vsemC(SEXP parSEXP, SEXP PARSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type PAR(PARSEXP);
    __result = Rcpp::wrap(vsemC(par, PAR));
    return __result;
END_RCPP
}
