png(filename = "/man/figures/betaDensity.png", width = 400, height = 300)
plot(density(rbeta(10000000,10,3)), main = "Beta Density with a = 10, b = 3")
dev.off()
png(filename = "/BayesianTools/Bayesiantools/man/figures/normalDensity.png", width = 400, height = 300)
plot(density(rnorm(10000000,0,1)), main = "Normal Density with mean = 0, sd = 1")
dev.off()
png(filename = "/BayesianTools/Bayesiantools/man/figures/uniformDensity.png", width = 400, height = 300)
plot(density(runif(10000000)), main = "Uniform Density")
dev.off()