# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C version of the VSEM model
#' @param par parameter vector
#' @param PAR 	Photosynthetically active radiation (PAR) MJ /m2 /day
#' @export
vsemC <- function(par, PAR) {
    .Call('BayesianTools_vsemC', PACKAGE = 'BayesianTools', par, PAR)
}

